"""Publish the generated dress set as parquet with embedded images.

The pictures are shipped inside the parquet rather than described by a link,
because they are generated by models released under Apache-2.0 and there is no
third party to point at.

Rows carry the generator that drew them, so a reader can tell which of the two
produced a picture and can hold either one back.  They also carry the outcome
of the post-generation rescue: a two-model screening verdict (`rescue_ok`,
`rescue_flaws`) and, for the rows that pass, a caption written from the pixels
rather than from the generation prompt (`caption_rescued`).

Run on the machine that holds the images ($W is the shared workspace root,
$ARTFLOW_ROOT):

    HF_TOKEN=... python -m scripts.data.publish_hf_synth \\
        --records $W/data/synth/gen-ernie-image-turbo $W/data/synth/gen-qwen-image-lightning \\
        --verdicts verdicts_union.jsonl --rescued-captions captions_full.jsonl \\
        --out $W/hf_synth_staging --upload
"""

from __future__ import annotations

import argparse
import json
import os
from collections import Counter
from pathlib import Path
from typing import Dict, List, Tuple

import pyarrow as pa
import pyarrow.parquet as pq

REPO_ID = "kaupane/east-asian-dress-synthetic"
COLUMNS = ["image_id", "text", "language", "family", "subject", "subject_group",
           "aspect", "width", "height", "generator", "steps", "seconds"]
# Generation records name the recipe that ran, which is not what a reader of the
# dataset is looking for; this is the model each recipe draws with.
GENERATORS = {
    "ernie-image-turbo": "ERNIE-Image-Turbo",
    "qwen-image-lightning": "Qwen-Image with the 8-step distilled sampler",
    "qwen-image": "Qwen-Image",
    "z-image": "Z-Image-Turbo",
}

SCHEMA = pa.schema([
    ("image_id", pa.string()),
    ("text", pa.string()),
    ("language", pa.string()),
    ("family", pa.string()),
    ("subject", pa.string()),
    ("subject_group", pa.string()),
    ("aspect", pa.string()),
    ("width", pa.int32()),
    ("height", pa.int32()),
    ("generator", pa.string()),
    ("steps", pa.int32()),
    ("seconds", pa.float32()),
    ("rescue_ok", pa.bool_()),
    ("rescue_flaws", pa.list_(pa.string())),
    ("caption_rescued", pa.string()),
    ("image", pa.struct([("bytes", pa.binary()), ("path", pa.string())])),
])

# The dataset viewer takes column types from the "huggingface" key of the
# parquet schema metadata.  Without it the image column reads as a struct of
# bytes and the viewer cannot render thumbnails.
FEATURES = {name: {"dtype": "string", "_type": "Value"} for name in COLUMNS}
FEATURES["width"] = {"dtype": "int32", "_type": "Value"}
FEATURES["height"] = {"dtype": "int32", "_type": "Value"}
FEATURES["steps"] = {"dtype": "int32", "_type": "Value"}
FEATURES["seconds"] = {"dtype": "float32", "_type": "Value"}
FEATURES["rescue_ok"] = {"dtype": "bool", "_type": "Value"}
FEATURES["rescue_flaws"] = {"feature": {"dtype": "string", "_type": "Value"},
                            "_type": "Sequence"}
FEATURES["caption_rescued"] = {"dtype": "string", "_type": "Value"}
FEATURES["image"] = {"_type": "Image"}

CARD = """---
license: apache-2.0
task_categories:
  - text-to-image
  - image-to-text
language:
  - zh
  - en
tags:
  - synthetic
  - portrait
  - clothing
  - east-asian
size_categories:
  - 10K<n<100K
---

# East Asian dress, generated

{pictures} generated pictures of people, each with the prompt it was made from
as its caption.  The set covers people from East, South-East and Central Asia
and the garments that have their own name - hanfu by period, the festival dress
of a number of ethnic groups in China, and the dress of neighbouring countries -
alongside ordinary modern clothing, in both photographs and paintings.

## What a row holds

| column | meaning |
|---|---|
| `image_id` | stable identifier, `syn-<index>` |
| `text` | the prompt the picture was made from, and its caption |
| `language` | `zh` or `en`; the caption is written in the language it names |
| `family` | `photograph` or `painting` |
| `subject` | the garment slot, e.g. `hanfu-ming`, `miao-silver` |
| `subject_group` | `hanfu`, `minority`, `neighbour` or `modern` |
| `aspect` | frame shape, one of `1x1`, `3x2`, `2x3`, `16x9`, `9x16` |
| `width`, `height` | dimensions of the picture |
| `generator` | which model drew it |
| `steps` | sampler steps used |
| `seconds` | wall-clock seconds the picture took |
| `rescue_ok` | whether the picture passed the quality screening below |
| `rescue_flaws` | which defect classes the screening found; empty for passing rows |
| `caption_rescued` | a fresh caption written from the pixels for passing rows; empty for rows that failed screening |

## How it was built

1. **Grid** - {prompts} prompts were generated by filling a slot template:
   a subject (a person and a garment), a setting, a framing, a light, and for
   photographs a camera style or for paintings a painting style and a mount.
   Combinations are drawn only where they make sense - a studio backdrop never
   accompanies a grasslands scene, candlelight never accompanies an outdoor
   one.  Each row of the grid is used twice, as the request to the generator
   and as the caption of the result, which is why the wording reads as something
   a person would ask for rather than as a tag list.
2. **Generation** - {generators} rendered the grid between them.  The prompts
   were split {split} so that neither model dominates any part of the grid:
   inside every combination of language, family, subject group and frame shape
   the two took equal turns.  Pictures are generated at the frame sizes the
   models were trained on, so nothing is rescaled.
3. **Screening and re-captioning** - after generation, every picture was shown
   to two vision-language models (Gemini 2.5 Flash Lite and Gemini 3.1 Flash
   Lite) with a checklist of fatal generation defects: broken anatomy, people
   fused together or missing parts, clothing drawn for the wrong facing,
   garbled pseudo-text, the same person cloned across the frame, studio
   equipment or a photographer's hand intruding into the scene, and the picture
   nested inside a drawn frame, book page, hanging scroll or fan border.  A row
   passes (`rescue_ok = true`) only when both models find none of these;
   {kept} of {pictures} rows pass.  The flaw labels found are kept in
   `rescue_flaws`.  Passing rows were then shown to the same models once more,
   without the generation prompt, to write `caption_rescued` - a description of
   what the picture actually shows rather than what was asked for, in the
   language of the original caption, at one of four length tiers.  The original
   prompt-as-caption in `text` is kept unchanged for reference.

## Using it

```python
from datasets import load_dataset
ds = load_dataset("{repo}", split="train")
row = ds[0]
row["image"].save("first.jpg")
print(row["text"], row["generator"])
# the screened, re-captioned subset:
good = ds.filter(lambda r: r["rescue_ok"])
print(good[0]["caption_rescued"])
```

## Licensing

The pictures were generated by {generators}, both released under Apache-2.0,
which places no restriction on their output.  The prompts were written for this
dataset and are released under CC-BY-4.0.

## Caveats

- These are generated pictures, not photographs of real people and not records
  of real garments.  Garment details are as accurate as the generators are;
  expect period and regional errors.
- Both generators have their own house style, and a model trained on this set
  will pick some of it up.  The two-way split is there to spread that out, not
  to remove it.
- The grid covers a chosen list of garments and regions.  It is not a survey,
  and the proportion of each subject in the grid is a choice, not a finding.
"""


def read_records(directories: List[str]) -> List[Dict]:
    rows = []
    for directory in directories:
        for path in sorted(Path(directory).glob("generated_shard*.jsonl")):
            with path.open(encoding="utf-8") as handle:
                for line in handle:
                    line = line.strip()
                    if line:
                        rows.append(json.loads(line))
    return rows


def load_verdicts(path: str) -> Dict[str, Dict]:
    """image_id -> {\"ok\": bool, \"flaws\": [...]} from the screening output."""
    verdicts = {}
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                record = json.loads(line)
                verdicts[record["image_id"]] = {
                    "ok": bool(record.get("ok")),
                    "flaws": [str(f) for f in (record.get("flaws") or [])],
                }
    return verdicts


def load_rescued_captions(path: str) -> Dict[str, str]:
    """image_id -> accepted caption text from the re-captioning output."""
    captions = {}
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                record = json.loads(line)
                if record.get("accepted") and record.get("text"):
                    captions[record["image_id"]] = record["text"]
    return captions


def build_rows(records: List[Dict], verdicts: Dict[str, Dict],
               rescued: Dict[str, str]) -> Tuple[List[Dict], Counter]:
    """Rows ready for parquet, with the picture bytes read in."""
    stats = Counter()
    seen = set()
    rows = []
    for record in sorted(records, key=lambda item: item["prompt_id"]):
        image_id = record["image_id"]
        if image_id in seen:
            stats["duplicate record"] += 1
            continue
        seen.add(image_id)
        path = Path(record["path"])
        if not path.is_file():
            stats["image missing"] += 1
            continue
        row = {key: record.get(key) for key in COLUMNS if key != "image"}
        recipe = record.get("generator") or record.get("recipe")
        row["generator"] = GENERATORS.get(recipe, recipe)
        row["seconds"] = float(record["seconds"]) if record.get("seconds") else None
        verdict = verdicts.get(image_id)
        if verdict is None:
            stats["no verdict"] += 1
        row["rescue_ok"] = bool(verdict and verdict["ok"])
        row["rescue_flaws"] = verdict["flaws"] if verdict else []
        row["caption_rescued"] = rescued.get(image_id, "")
        row["image"] = {"bytes": path.read_bytes(), "path": path.name}
        rows.append(row)
    return rows, stats


def write_shards(rows: List[Dict], out_dir: Path, shard_gb: float,
                 row_group_rows: int) -> List[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    metadata = {b"huggingface": json.dumps({"info": {"features": FEATURES}}).encode()}
    limit = int(shard_gb * 1024 ** 3)
    written: List[Path] = []
    batch: List[Dict] = []
    size = 0

    def flush() -> None:
        nonlocal batch, size
        if not batch:
            return
        table = pa.Table.from_pylist(batch, schema=SCHEMA)
        table = table.replace_schema_metadata(metadata)
        path = out_dir / f"train-{len(written):05d}-of-shards.parquet"
        pq.write_table(table, path, compression="zstd", row_group_size=row_group_rows,
                       write_page_index=True)
        written.append(path)
        print(f"  {path.name}: {len(batch)} rows ({path.stat().st_size / 1e9:.2f} GB)",
              flush=True)
        batch = []
        size = 0

    for row in rows:
        batch.append(row)
        size += len(row["image"]["bytes"])
        if size >= limit:
            flush()
    flush()
    # Rename to the "of N" convention once N is known.
    total = len(written)
    renamed = []
    for index, path in enumerate(written):
        target = path.with_name(f"train-{index:05d}-of-{total:05d}.parquet")
        path.rename(target)
        renamed.append(target)
    return renamed


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--records", required=True, nargs="+")
    parser.add_argument("--verdicts", required=True,
                        help="union screening verdicts JSONL (image_id, ok, flaws)")
    parser.add_argument("--rescued-captions", required=True,
                        help="re-captioning output JSONL (image_id, accepted, text)")
    parser.add_argument("--out", required=True, help="staging directory")
    parser.add_argument("--shard-gb", type=float, default=1.0)
    parser.add_argument("--row-group-rows", type=int, default=16)
    parser.add_argument("--upload", action="store_true")
    args = parser.parse_args()

    records = read_records(args.records)
    verdicts = load_verdicts(args.verdicts)
    rescued = load_rescued_captions(args.rescued_captions)
    rows, stats = build_rows(records, verdicts, rescued)
    print(f"{len(records)} records -> {len(rows)} rows "
          f"({sum(row['rescue_ok'] for row in rows)} pass screening, "
          f"{sum(bool(row['caption_rescued']) for row in rows)} re-captioned)")
    for key, count in stats.most_common():
        print(f"  {key}: {count}")

    out = Path(args.out)
    shards = write_shards(rows, out / "data", args.shard_gb, args.row_group_rows)
    generators = sorted({row["generator"] for row in rows})
    print(f"generators: {generators}")
    print(f"rows per generator: {dict(Counter(row['generator'] for row in rows))}")
    print(f"language: {dict(Counter(row['language'] for row in rows))}")
    print(f"family: {dict(Counter(row['family'] for row in rows))}")

    card = CARD.format(
        pictures=f"{len(rows):,}",
        kept=f"{sum(row['rescue_ok'] for row in rows):,}",
        prompts=f"{len(rows):,}",
        generators=" and ".join(f"`{name}`" for name in generators),
        split="evenly",
        repo=REPO_ID,
    )
    (out / "README.md").write_text(card, encoding="utf-8")
    print(f"wrote {out/'README.md'} and {len(shards)} shards")

    if args.upload:
        from huggingface_hub import HfApi

        api = HfApi(token=os.environ["HF_TOKEN"])
        api.create_repo(REPO_ID, repo_type="dataset", exist_ok=True)
        api.upload_folder(folder_path=str(out), repo_id=REPO_ID, repo_type="dataset")
        print(f"uploaded to {REPO_ID}")


if __name__ == "__main__":
    main()
