"""Audit generated pictures against their prompts, and caption the mismatches.

A synthetic row is only usable as training data if its text describes what the
picture actually shows.  This batch checks every row on that question and then
acts on the answer:

1. ``check``   - a vision model compares each picture with the prompt that
   asked for it and reports what is missing or contradicted.  A picture that
   carries everything the prompt asked for (verdict ``full`` or ``mostly``,
   nothing contradicted) keeps the prompt as its caption.
2. ``caption`` - every other picture is captioned from the image itself, under
   the same caption contract as the harvested corpus, so the row stays a true
   image/text pair instead of a record of a failed generation.
3. ``assemble`` - one manifest row per picture: the caption list training
   consumes, and the provenance (seed, axis, verdict) needed to audit it.
4. ``sheet``   - contact sheets of a deterministic sample, for looking at.

Requests are cached by the shared caption client, so a re-run costs nothing.

CLI:
    python -m scripts.data.qa_synth_batch --stage all \\
        --generated $W/data/synth/qwen21/images --grid data/hpsv2/grid.jsonl \\
        --out-dir $W/data/synth/qwen21/qa --model deepseek:deepseek-flash
"""

from __future__ import annotations

import argparse
import asyncio
import json
import math
from collections import Counter
from pathlib import Path
from typing import Dict, List

import httpx

from src.dataset.caption_client import CaptionClient, Response, encode_image, summarise
from src.dataset.caption_prompts import CaptionRequest, check_caption, normalize_caption

CHECK_VERSION = "synth-check-v1"
CAPTION_VERSION = "synth-caption-v1"

CHECK_PROMPT = """You are auditing one picture generated by a text-to-image model against the prompt that asked for it.

Prompt: {prompt}

Judge only what is visible in the picture. Report as JSON:
{{"verdict": "full" | "mostly" | "partial" | "none",
  "missing": ["<element the prompt describes that is not visible>", ...],
  "contradicted": ["<element the prompt describes differently from the picture>", ...]}}

Verdicts:
- full: everything the prompt asks for is visible, nothing is contradicted.
- mostly: everything important is visible; at most one secondary element is missing or wrong.
- partial: several described elements are missing, wrong or unreadable.
- none: the picture does not show the prompt's subject at all.

Do not penalise the picture for showing things the prompt did not mention. Do not judge quality, style or prompt-making. A caption may state an element more specifically than the picture shows - that is "mostly" at worst, never "contradicted". Return JSON only."""

CAPTION_NOTE = ("This picture was generated by a text-to-image model from a different "
                "prompt, so it may differ from any text you have seen. Describe what is "
                "in the picture.")


def read_jsonl(path: Path) -> List[Dict]:
    return [json.loads(line) for line in path.open(encoding="utf-8") if line.strip()]


def load_rows(grid_path: Path, generated_dir: Path) -> List[Dict]:
    """Grid rows joined with the generator's record of what it rendered."""
    grid = {row["prompt_id"]: row for row in read_jsonl(grid_path)}
    rows = []
    for shard in sorted(generated_dir.glob("generated_shard*.jsonl")):
        for record in read_jsonl(shard):
            row = dict(grid.get(record["prompt_id"], {}))
            row.update({k: v for k, v in record.items() if k in
                        ("path", "seconds", "skipped", "recipe", "steps", "width", "height")})
            row["prompt_id"] = record["prompt_id"]
            rows.append(row)
    rows.sort(key=lambda row: row["prompt_id"])
    return rows


def parse_json(text: str) -> Dict:
    start, end = text.find("{"), text.rfind("}")
    if start < 0 or end <= start:
        raise ValueError(f"no JSON object: {text[:160]!r}")
    return json.loads(text[start:end + 1])


async def check_row(client: CaptionClient, http: httpx.AsyncClient, row: Dict) -> Dict:
    image_bytes = encode_image(row["path"])
    response = await client.generate(
        http, image_bytes=image_bytes,
        prompt=CHECK_PROMPT.format(prompt=row["text"]),
        prompt_version=CHECK_VERSION, max_tokens=700, temperature=0.0,
        extra={"reasoning_effort": "none"})
    out = {"prompt_id": row["prompt_id"], "prompt": row["text"], "language": row["language"],
           "band": row["band"], "format": row["format"], "seed_prompt": row.get("seed_prompt"),
           "subject_group": row.get("subject_group"), "path": row["path"]}
    if response.error:
        out["verdict"] = "error"
        out["error"] = response.error
    else:
        try:
            parsed = parse_json(response.text)
            out["verdict"] = str(parsed.get("verdict", "partial")).strip().lower()
            out["missing"] = parsed.get("missing") or []
            out["contradicted"] = parsed.get("contradicted") or []
        except (ValueError, KeyError) as exc:
            out["verdict"] = "error"
            out["error"] = f"parse: {exc}"
    out["image_tokens"] = response.prompt_tokens
    return out, response


def needs_caption(check: Dict) -> bool:
    """A picture is captioned from itself unless the prompt already fits it."""
    if check.get("verdict") in ("partial", "none", "error"):
        return True
    return bool(check.get("contradicted"))


async def caption_row(client: CaptionClient, http: httpx.AsyncClient, check: Dict) -> Dict:
    request = CaptionRequest(image_id=check["prompt_id"], language=check["language"],
                             format=check["format"], band=check["band"], domain="generic",
                             extra_notes="\n" + CAPTION_NOTE)
    image_bytes = encode_image(check["path"])
    out = dict(check)
    for attempt in range(2):
        response = await client.generate(
            http, image_bytes=image_bytes, prompt=request.prompt(),
            prompt_version=request.prompt_version, max_tokens=4096, temperature=0.4,
            extra={"reasoning_effort": "none"})
        if response.error:
            out["caption_error"] = response.error
            continue
        cleaned = normalize_caption(response.text)
        result = check_caption(cleaned, request, None)
        out.update({"caption": cleaned, "caption_prompt_version": request.prompt_version,
                    "caption_tokens": result.retained_tokens, "caption_in_band": result.in_band,
                    "caption_evaluation_hits": result.evaluation_hits,
                    "caption_hedging_hits": result.hedging_hits})
        out.pop("caption_error", None)
        if result.ok:
            # Hedging and evaluation phrases are measured per batch, exactly as
            # they are for the harvested corpus; only a defect of the text
            # itself (a repeated sentence, an empty answer) is re-asked.
            break
        out.pop("caption", None)
    return out, response


def report_cost(verb: str, responses: List[Response]) -> None:
    summary = summarise(responses)
    print(f"{verb}: {summary['requests']} calls, {summary['billed_requests']} billed, "
          f"{summary['errors']} errors, ${summary['cost_usd']:.2f}, "
          f"mean latency {summary['mean_latency_s']:.1f}s")


async def stage_check(args, rows: List[Dict]) -> List[Dict]:
    client = CaptionClient(cache_dir=args.cache, model=args.model, concurrency=args.concurrency)
    results, responses = [], []
    out_path = args.out_dir / "checks.jsonl"
    with out_path.open("w", encoding="utf-8") as sink:
        async with httpx.AsyncClient() as http:
            for start in range(0, len(rows), args.batch):
                batch = rows[start:start + args.batch]
                done = await asyncio.gather(*[check_row(client, http, row) for row in batch])
                for record, response in done:
                    sink.write(json.dumps(record, ensure_ascii=False) + "\n")
                    responses.append(response)
                sink.flush()
                results.extend(record for record, _ in done)
                print(f"  checked {len(results)}/{len(rows)}", flush=True)
    verdicts = Counter(record["verdict"] for record in results)
    print("verdicts: " + "  ".join(f"{k} {v}" for k, v in verdicts.most_common()))
    report_cost("check", responses)
    return results


async def stage_caption(args, checks: List[Dict]) -> List[Dict]:
    todo = [check for check in checks if needs_caption(check)]
    print(f"{len(todo)} of {len(checks)} rows need a caption from the image")
    client = CaptionClient(cache_dir=args.cache, model=args.model, concurrency=args.concurrency)
    out, responses = [], []
    out_path = args.out_dir / "captions.jsonl"
    with out_path.open("w", encoding="utf-8") as sink:
        async with httpx.AsyncClient() as http:
            for start in range(0, len(todo), args.batch):
                batch = todo[start:start + args.batch]
                done = await asyncio.gather(*[caption_row(client, http, check) for check in batch])
                for record, response in done:
                    sink.write(json.dumps(record, ensure_ascii=False) + "\n")
                    responses.append(response)
                sink.flush()
                out.extend(record for record, _ in done)
                print(f"  captioned {len(out)}/{len(todo)}", flush=True)
    failures = sum(1 for record in out if not record.get("caption"))
    print(f"captions written: {len(out) - failures}, failures: {failures}")
    report_cost("caption", responses)
    return out


def stage_assemble(args, checks: List[Dict]) -> None:
    captions = {record["prompt_id"]: record for record in
                read_jsonl(args.out_dir / "captions.jsonl")} if (args.out_dir / "captions.jsonl").exists() else {}
    out_path = args.out_dir / "manifest.jsonl"
    sources = Counter()
    with out_path.open("w", encoding="utf-8") as sink:
        for check in checks:
            caption = captions.get(check["prompt_id"])
            if caption and caption.get("caption"):
                texts, source = [caption["caption"]], "image"
            else:
                texts, source = [check["prompt"]], "prompt"
            sources[source] += 1
            sink.write(json.dumps({
                "image_id": check["prompt_id"],
                "local_path": check["path"],
                "captions": texts,
                "caption_source": source,
                "verdict": check["verdict"],
                "missing": check.get("missing", []),
                "contradicted": check.get("contradicted", []),
                "language": check["language"], "band": check["band"], "format": check["format"],
                "prompt_version": (caption or {}).get("caption_prompt_version", CHECK_VERSION),
                "source": "hpsv2-qwen21",
                "seed_prompt": check.get("seed_prompt"),
                "axis": check.get("subject_group"),
            }, ensure_ascii=False) + "\n")
    total = sum(sources.values())
    print(f"manifest: {total} rows -> {out_path}")
    print("  caption source: " + "  ".join(f"{k} {v} ({v / max(total, 1):.1%})"
                                           for k, v in sources.most_common()))


def stage_sheet(args, checks: List[Dict]) -> None:
    from PIL import Image, ImageDraw

    sheets_dir = args.out_dir / "sheets"
    sheets_dir.mkdir(parents=True, exist_ok=True)
    want = max(args.sheets, 1) * args.per_sheet
    step = max(len(checks) // want, 1)
    sample = checks[::step][:want]
    for index in range(0, len(sample), args.per_sheet):
        chunk = sample[index:index + args.per_sheet]
        tiles = []
        for record in chunk:
            image = Image.open(record["path"]).convert("RGB")
            image.thumbnail((args.tile, args.tile))
            tile = Image.new("RGB", (args.tile, args.tile + 18), "white")
            tile.paste(image, ((args.tile - image.width) // 2, 0))
            draw = ImageDraw.Draw(tile)
            draw.text((4, args.tile + 3),
                      f"{record['prompt_id']} {record.get('verdict', '')}", fill="black")
            tiles.append(tile)
        cols = int(math.ceil(math.sqrt(len(tiles))))
        rows = int(math.ceil(len(tiles) / cols))
        sheet = Image.new("RGB", (cols * args.tile, rows * (args.tile + 18)), "white")
        for position, tile in enumerate(tiles):
            sheet.paste(tile, ((position % cols) * args.tile, (position // cols) * (args.tile + 18)))
        name = sheets_dir / f"sheet-{index // args.per_sheet:02d}.jpg"
        sheet.save(name, quality=88)
        print(f"  {name} ({len(tiles)} tiles)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--stage", default="all",
                        choices=["check", "caption", "assemble", "sheet", "all"])
    parser.add_argument("--generated", required=True, help="directory with generated_shard*.jsonl")
    parser.add_argument("--grid", default="data/hpsv2/grid.jsonl")
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--cache", default=None, help="caption cache (default: <out-dir>/cache)")
    parser.add_argument("--model", default="deepseek:deepseek-flash")
    parser.add_argument("--concurrency", type=int, default=48)
    parser.add_argument("--batch", type=int, default=2000)
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--sheets", type=int, default=8)
    parser.add_argument("--per-sheet", type=int, default=24)
    parser.add_argument("--tile", type=int, default=320)
    args = parser.parse_args()
    args.out_dir = Path(args.out_dir)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    args.cache = Path(args.cache) if args.cache else args.out_dir / "cache"

    rows = load_rows(Path(args.grid), Path(args.generated))
    if args.limit:
        rows = rows[:args.limit]
    print(f"{len(rows)} generated rows under {args.generated}")

    if args.stage in ("check", "all"):
        stage_check(args, rows)
    checks = read_jsonl(args.out_dir / "checks.jsonl")
    if args.stage in ("caption", "all"):
        stage_caption(args, checks)
    if args.stage in ("assemble", "all"):
        stage_assemble(args, checks)
    if args.stage in ("sheet", "all"):
        stage_sheet(args, checks)


if __name__ == "__main__":
    main()
